### ISSUE TITLE
Naming Conflicts

### ISSUE THREAD

**Issue by roastchicken** [mrpotatofactory/WonderfulWarnings#1]
Garry's Mod lua files are loaded into a virtual directory. All the files/folders in addons/addon/lua/ will be put in this directory, meaning that any files that have the same names will cause things to mess up. Please either put your lua files in their own directory (addons/wonderfulwarnings/lua/wws/ and addons/wonderfulwarnings/lua/autorun/wws/ for example) or make them unique. Specifically, autorun/config.lua is likely to cause conflicts with other addons that have poorly named files. ulx.lua and aowl.lua might also cause conflicts.

**Comment by moonexpr** [comment]
Thanks! I'll be sure to resolve this in a few hours.

**Comment by roastchicken** [comment]
Thanks for resolving the issue so quickly, however you're not completely in the clear.

You still have a naming conflict with autorun/config. Autorun lua files are still in a virtual directory and will still cause naming conflicts just like any other file. Either put the config file in it's own (unique) directory or give it a unique name.

**Comment by moonexpr** [comment]
I'll be back to fix the issue in a week.
I'm going to be out of state

**Comment by austinhanna** [comment]
Fixed it. Accept the pull request. @roastchicken @mrpotatofactory

**Comment by moonexpr** [comment]
Merged. Thanks @AustinHnn
